version: 2

machine:
  environment:
    QEMU_AUDIO_DRV: none

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    pre:
      - run: ./ci/permissions.sh
    steps:
      - checkout
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}
      - run:
          name: Build Project
          command: ./ci/build.sh
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    pre:
      - run: ./ci/permissions.sh
      - emulator -avd circleci-android24 -no-window:
          background: true
          parallel: true
      - circle-android wait-for-boot
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}
      - run:
          name: Execute Tests
          command: ./ci/test.sh

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build