version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Grant Permissions
          command: ./ci/permissions.sh
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}
      - run:
          name: Build Project
          command: ./gradlew assembleDebug
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Grant Permissions
          command: ./ci/permissions.sh
      - run:
          name: Execute Tests
          command: ./ci/tests.sh
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}
      - run:
          name: Grant Permissions
          command: ./ci/permissions.sh
      - run:
          name: Deploy Artifacts
          command: ./ci/deploy.sh

workflows:
  version: 2
  feature:
    jobs:
      - build
      - test:
          requires:
            - build
    branches:
      only:
        - /^feature.*$/
  release:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
    branches:
      only:
        - /^release.*$/