version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Grant Permissions
          command: ./ci/permissions.sh
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}
      - run:
          name: Build Project
          command: ./gradlew assembleDebug
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Grant Permissions
          command: ./ci/permissions.sh
      - run:
          name: Execute Tests
          command: ./ci/tests.sh

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build