version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Grant Permissions
          command: ./ci/permissions.sh
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}
      - run:
          name: Build Project
          command: ./ci/build.sh
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}
      - run:
          name: Grant Permissions
          command: ./ci/permissions.sh
      - run:
          name: Execute Tests
          command: ./ci/test.sh

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build